/*
===============================================
Pathos Engine - Copyright Andrew Lucas

2016-2024
All Rights Reserved.
===============================================
*/

#ifndef ENTITY_ENUMS_H
#define ENTITY_ENUMS_H

enum scripted_sequence_anim_t
{
	SCRIPT_SEQ_PLAY = 0,
	SCRIPT_SEQ_LOOP,
	SCRIPT_SEQ_LOOP_EXIT
};

enum ai_condition_bits_t
{
	AI_COND_NO_AMMO_LOADED = 0,
	AI_COND_SEE_HATE,
	AI_COND_SEE_FEAR,
	AI_COND_SEE_DISLIKE,
	AI_COND_SEE_ENEMY,
	AI_COND_ENEMY_OCCLUDED,
	AI_COND_SMELL_FOOD,
	AI_COND_ENEMY_TOO_FAR,
	AI_COND_LIGHT_DAMAGE,
	AI_COND_HEAVY_DAMAGE,
	AI_COND_CAN_RANGE_ATTACK1,
	AI_COND_CAN_RANGE_ATTACK2,
	AI_COND_CAN_MELEE_ATTACK1,
	AI_COND_CAN_MELEE_ATTACK2,
	AI_COND_FOLLOW_TARGET_TOO_FAR,
	AI_COND_PROVOKED,
	AI_COND_NEW_ENEMY,
	AI_COND_HEAR_SOUND,
	AI_COND_SMELL,
	AI_COND_ENEMY_FACING_ME,
	AI_COND_ENEMY_DEAD,
	AI_COND_SEE_CLIENT,
	AI_COND_SEE_NEMESIS,
	AI_COND_ENEMY_NOT_FOUND,
	AI_COND_ENEMY_UNREACHABLE,
	AI_COND_IN_DANGER,
	AI_COND_DANGEROUS_ENEMY_CLOSE,
	AI_COND_BLOCKING_PATH,
	AI_COND_TASK_FAILED,
	AI_COND_SCHEDULE_DONE,
	AI_COND_CLIENT_UNSEEN,
	AI_COND_PLAYER_CLOSE,
	AI_COND_FRIENDLY_FIRE,
	AI_COND_ENEMY_NAVIGABLE,
	AI_COND_ELOF_FAILED,
	AI_COND_HEARD_ENEMY_NEW_POSITION,
	AI_COND_RESERVED1,
	AI_COND_RESERVED2,
	AI_COND_RESERVED3,
	AI_COND_RESERVED4,
	AI_COND_NOT_ONGROUND,
	AI_COND_SHOOT_VECTOR_VALID,
	AI_COND_CAN_SPECIAL_ATTACK1,
	AI_COND_CAN_SPECIAL_ATTACK2,
	AI_COND_SEE_HOSTILE_NPC,

	AI_COND_BITSET_SIZE = 64
};

#endif // ENTITY_ENUMS_H
